
spring:
  application:
    name: gateway-service
  cloud:
   gateway:
     routes:
       - id: member-service
         uri: http://localhost:8081
         predicates:
           - Path=/member/**
           #- Path=/evaluation/**
           #- Path=/position/**
       - id: paiement-service
         uri: http://localhost:8080
         predicates:
           - Path=/payment/**
           #- Path=/orderItem/**
           #- Path=/cart/**


   

     default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
     globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"






