
spring:
  application:
    name: gateway-service
  cloud:
   gateway:
     routes:
#----------Member-------------------
       - id: member-service
         uri: http://localhost:8081
         predicates:
           - Path=/member/**

#----------Security------------------
       - id: security-service
         uri: http://localhost:8082
         predicates:
           - Path=/api/keycloak/**

#------------Payment------------------
       - id: paiement-service
         uri: http://localhost:8083
         predicates:
           - Path=/payment/**

#-----------Forum---------------------
       - id: forum-service
         uri: http://localhost:8084
         predicates:
           - Path=/forum/**

#-----------Project-------------------
       - id: project-service
         uri: http://localhost:8091
         predicates:
           - Path=/project/**

#-----------Cours---------------------
       - id: cours-service
         uri: http://localhost:8090
         predicates:
           - Path=/cours/**

       #-----------Evaluation---------------------
       - id: evaluation-service
         uri: http://localhost:8094
         predicates:
           - Path=/evaluation/**
        #-----------Notification---------------------
       - id: notification-service
         uri: http://localhost:8085
         predicates:
           - Path=/**



     default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
     globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"






